name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # hoặc branch bạn muốn trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ec2-user/flashcardd-app/FlashcardApp_BE
          git pull origin main
          docker stop flascardApp-be || true
          docker rm flascardApp-be || true
          docker build -t flascardApp-be .
          docker run -d --name flascardApp-be -p 9090:9090 --env-file .env flascardApp-be